In [114]:
import numpy as np

In [115]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
mat2D10 = mat2D * 10

In [116]:
print(f"Matriks 1D :\n {mat1D}")
print(f"Matriks 1D index ke 7:{mat1D[7]}")
print(f"Matriks 1D * 10 : {mat1D * 10}")

Matriks 1D :
 [1 2 3 4 5 6 7 8 9]
Matriks 1D index ke 7:8
Matriks 1D * 10 : [10 20 30 40 50 60 70 80 90]


In [117]:
print(f"Matriks 2D:\n{mat2D}")
print(f"Matriks 2D * 10 :\n{mat2D * 10}")
print(mat2D10[0])
print(mat2D10[0][2])

Matriks 2D:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matriks 2D * 10 :
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[10 20 30]
30


In [118]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(4, 3)


In [119]:
print(f"Ukuran dari mat1D :{mat1D.size}")
print(f"Ukuran dari mat2D :{mat2D.size}")

Ukuran dari mat1D :9
Ukuran dari mat2D :12


In [150]:
#Spesial matrix
mZero = np.zeros((3,3))
mOne = np.ones((3,3))
mFull = np.full((4,4),7) #Membuat array dengan ukuran 4*4 dengan diisi nilai 7
mIdentity = np.eye((4))
mFRandom1D = np.random.rand(5)
mFRandom2D = np.random.rand(3,3)
mIRandom1D = np.random.randint(10,100,size=5)
mIRandom2D = np.random.randint(10,100,size=(4,4))

print(f"Matriks mZero :\n{mZero}")
print(f"Matriks mOne :\n{mOne}")
print(f"Matriks mFull :\n{mFull}")
print(f"Matriks Identitas:\n{mIdentity}")
print(f"Matriks mFRandom1D:\n{mFRandom1D}")
print(f"Matriks mFRandom2D:\n{mFRandom2D}")
print(f"Matriks mIRandom1D:\n{mIRandom1D}")
print(f"Matriks mIRandom2D:\n{mIRandom2D}")

Matriks mZero :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Matriks mOne :
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Matriks mFull :
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Matriks Identitas:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matriks mFRandom1D:
[0.64624117 0.07618324 0.37612807 0.03903807 0.69039562]
Matriks mFRandom2D:
[[0.73321946 0.63326025 0.56041728]
 [0.10050495 0.06391388 0.675371  ]
 [0.12778075 0.67598688 0.69436407]]
Matriks mIRandom1D:
[56 56 86 51 51]
Matriks mIRandom2D:
[[50 35 22 94]
 [28 30 47 86]
 [29 84 97 60]
 [10 49 12 28]]


In [160]:
#Mengubah bentuk array
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
mshape = data.reshape((9,1))
mFlat = data.flatten()

print(f"Maatriks data:\n{data}")
print(f"Matriks reshape:\n {mshape}")
print(f"Matriks mFlate:\n {mFlat}")

Maatriks data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriks reshape:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Matriks mFlate:
 [1 2 3 4 5 6 7 8 9]


In [180]:
#Deskriptif Statistik
x = np.array([1,2,3,4])
y = np.array([2,5,7,9])

#Menghitung dot product
r1 = np.dot(x,y)
r2 = np.add(x,y)

print(f"Hasil dari dot product:{r1}")
print(f"Hasil penjumlahan matriks:\n{r2}")
print(f"Nilai minimum :{y.min()}")
print(f"Nilai maksimum :{y.max()}")
print(f"Nilai rata rata :{y.mean()}")
print(f"Nilai Total adalah :{y.sum()}")
print(f"Nilai Deviasi :{y.std()}")

Hasil dari dot product:69
Hasil penjumlahan matriks:
[ 3  7 10 13]
Nilai minimum :2
Nilai maksimum :9
Nilai rata rata :5.75
Nilai Total adalah :23
Nilai Deviasi :2.5860201081971503


In [200]:
#Filtering

nilaiPemograman = np.array([100,90,100,80,50,50,50,40])
#Tampilkan Nilai Pemograman yang lebih dari 50 -> LULUS
#Berapakah jumlah mahasiswa yang lulus
jmlLulus = nilaiPemograman [nilaiPemograman > 50]
print(jmlLulus)
print(f"Mahasiswa yang lulus sebanyak :{jmlLulus.size}")
print(f"Mahasiswa yang tidak lulus sebanyak :{nilaiPemograman.size-jmlLulus.size}")


[100  90 100  80]
Mahasiswa yang lulus sebanyak :4
Mahasiswa yang tidak lulus sebanyak :4


<b>Project Generate Data</b> <br>
Buatlah 1000 Data, yang akan digunakan untuk prediksi atau klasifikasi yaitu
<ol>
    <li>Usia : 17 - 60</li>
    <li>Gender : L/P</li>
    <li>Transaksi perBulan : 0-50</li>
    <li>Pembayaran: Buruk, Sedang, Bagus</li>
</ol>

In [240]:
import numpy as np
import pandas as pd
jmlData = 1000

usia = np.random.randint(17,61,size=jmlData)
gender = np.random.choice(['L','P'],size=jmlData)
transaksi = np.random.randint(0,51,size=jmlData)
pembayaran = np.random.choice(['Buruk','Sedang','Bagus'],size=jmlData)

df = pd.DataFrame({
    'usia' : usia,
    'gender' : gender,
    'transaksi' : transaksi,
    'pembayaran' : pembayaran
})

print(df)
print(df.info()) #Menampilkan karakteristik data
print(df.head()) #Menampilkan isi tabel 5 baris pertama
#Tampilkan usia yang paling muda
print(f"usia customer termuda:{df['usia'].min()}")
print(f"usia customer tertua:{df['usia'].max()}")
#Tanpilkan jumlah customer yang laki laki
jmlL = df[df['gender']=='L']
print(f"Jumlah Customer Laki-Laki: {jmlL.size/4}")
print(f"Jumlah Customer Laki-Laki:{jmlL['gender'].size}")
df.to_csv("dataCustomer.csv")

     usia gender  transaksi pembayaran
0      37      L          9      Buruk
1      27      L          9     Sedang
2      41      P         35      Buruk
3      60      L         33     Sedang
4      43      L          1     Sedang
..    ...    ...        ...        ...
995    19      P         18      Buruk
996    46      P          2      Buruk
997    54      P         31      Bagus
998    33      P          5      Bagus
999    51      P          6     Sedang

[1000 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   usia        1000 non-null   int32 
 1   gender      1000 non-null   object
 2   transaksi   1000 non-null   int32 
 3   pembayaran  1000 non-null   object
dtypes: int32(2), object(2)
memory usage: 23.6+ KB
None
   usia gender  transaksi pembayaran
0    37      L          9      Buruk
1    27      L          9     Se